name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t todoapp .

    - name: Run tests
      run: |
        docker run -w /app my-app npm install jest
        docker run -w /app my-app npx jest


    - name: Deploy to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app
